// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: LED

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Index
void ui_Index_screen_init(void);
lv_obj_t * ui_Index;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_money;
lv_obj_t * ui_Container1;
void ui_event_item1(lv_event_t * e);
lv_obj_t * ui_item1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label5;
void ui_event_item2(lv_event_t * e);
lv_obj_t * ui_item2;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label7;
void ui_event_item3(lv_event_t * e);
lv_obj_t * ui_item3;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label9;
lv_obj_t * ui_ok_btn;
lv_obj_t * ui_Label3;


// SCREEN: ui_ok
void ui_ok_screen_init(void);
lv_obj_t * ui_ok;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Label10;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_[3] = {&ui_img_1008930_png, &ui_img_1031411_png, &ui_img_1031953_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_item1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_item3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_item2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_item1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}
void ui_event_item2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_item3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_item2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_item1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_item3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_item3, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_item2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_item1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Index_screen_init();
    ui_ok_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Index);
}
