// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: LED

#ifndef _LED_UI_H
#define _LED_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Index
void ui_Index_screen_init(void);
extern lv_obj_t * ui_Index;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_money;
extern lv_obj_t * ui_Container1;
void ui_event_item1(lv_event_t * e);
extern lv_obj_t * ui_item1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label5;
void ui_event_item2(lv_event_t * e);
extern lv_obj_t * ui_item2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label7;
void ui_event_item3(lv_event_t * e);
extern lv_obj_t * ui_item3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_ok_btn;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_ok
void ui_ok_screen_init(void);
extern lv_obj_t * ui_ok;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1031953_png);    // assets/1031953.png
LV_IMG_DECLARE(ui_img_1008930_png);    // assets/1008930.png
LV_IMG_DECLARE(ui_img_1031411_png);    // assets/1031411.png
LV_IMG_DECLARE(ui_img_25474289);    // assets/done-icon.png



LV_FONT_DECLARE(ui_font_Kanit18);
LV_FONT_DECLARE(ui_font_Kanit24);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
